spring.application.name=ExamplProps1
server.port=8081

#Camel-Servlet
camel.servlet.mapping.context-path=/api/*

#Prospect to Sample Upgrade API
custom.groupregistratation.v2.groups.registration.uri=/corp/gateway/ifp/custom/upgrade/v2
custom.groupregistratation.v2.groups.registration.processor=direct:customSampleRegistrationRequestProcessor
custom.groupregistratation.v2.groups.registration.desc=This service is used to register a valid custom to group on the BSC Sample Portal

#Prospect to Sample Upgrade API Trigger
custom.upgrade.v2.retry.service.api.uri=/corp/gateway/customtogroup/upgrade/trigger/v2
custom.upgrade.v2.retry.service.api.processor=direct:customRetryProcessor
custom.upgrade.v2.retry.service.api.desc=This api is used to re-trigger the failed custom to group upgrade requests
custom.upgrade.v2.service.processor=seda:customUpgradeAPIRetry?concurrentConsumers=1

#PTM retry 
custom.upgrade.v2.retry.service.configuration.processFromDays=60
custom.upgrade.v2.retry.service.configuration.rowCount=100
custom.upgrade.v2.retry.service.configuration.lastUpdatedMinutes=10
custom.upgrade.v2.retry.service.configuration.minutes=1440
custom.upgrade.v2.retry.service.configuration.maxIterations=-1

#PTM proxy app service endpoint /corp/gateway/ifp/custom/upgrade/v2
custom.upgrade.v2.service.configuration.routingEndPoint=https://aasfd-3453m345454.azure-api.net/apim_proxy_echo_/private/opstest/api/corp/gateway/ifp/custom/upgrade/v3
custom.upgrade.v2.service.configuration.clientId=9a5cc6f34e06a95eca70982bb8ed228e
custom.upgrade.v2.service.configuration.clientSecret=037c99a96aed69b857aeff2bb488d82e
custom.upgrade.v2.service.configuration.jwt.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30

#PTM notification config
custom.upgrade.v2.retry.service.notification.from=defaultFrom
custom.upgrade.v2.retry.service.notification.to=bob@example.com
custom.upgrade.v2.retry.service.notification.subject=Test upgrade job status : opstest
custom.upgrade.v2.retry.service.notification.template=userSuppliedTemplate
custom.group.v2.registration.notification.uri=https://34545m4m4mm4m4m4.azurewebsites.net/api/corp/gateway/custom/sendnotification/cloud/v1
custom.group.v2.registration.notification.jwt.token.type=JWT
custom.group.v2.registration.notification.jwt.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30

#PTM RL Wrapper
custom.group.upgrade.v2.radinatwrapper.search.service.url=https://mm454-54mm4-4-4.azure-api.net/apim_proxy_echo_/private/opstest/api/corp/gateway/group/radiant/search/profile/v1
custom.group.upgrade.v2.radinatwrapper.movedn.service.url=https://mm454-54mm4-4-4.azure-api.net/apim_proxy_echo_/private/opstest/api/corp/gateway/group/radiant/move/profile/v1
custom.group.upgrade.v2.radinatwrapper.delete.service.url=https://mm454-54mm4-4-4.azure-api.net/apim_proxy_echo_/private/opstest/api/corp/gateway/group/radiant/delete/profile/v1
custom.group.upgrade.v2.radinatwrapper.update.service.url=https://mm454-54mm4-4-4.azure-api.net/apim_proxy_echo_/private/opstest/api/corp/gateway/group/radiant/update/profile/v1
custom.group.upgrade.v2.radinatwrapper.service.clientid=cb0b692c997bfbb8bd16427b51dd3eb0
custom.group.upgrade.v2.radinatwrapper.service.clientsecret=a063606c0869164d07bb4a5c86b29e37

#PTM Sample Info 
custom.groupregistratation.v2.group.lookup.url=https://mm454-54mm4-4-4.azure-api.net/apim_proxy_echo_/private/opstest/api/corp/gateway/group/info/v3
custom.groupregistratation.v2.group.lookup.jwt.token.type=plain_token
custom.groupregistratation.v2.group.lookup.jwt.token=aip_npe_lookupinfo
custom.groupregistratation.v2.groups.identity.lookup.uabt.group.groups=W0052201,W0052337,W0052202,W0052204

#PTM CCM
custom.group.v2.registration.api.ccm.core.url.plan.group.search=https://mm454-54mm4-4-4.azure-api.net/apim_proxy_echo_/private/opstest/api/corp/gateway/ccm/core/search/plan/groups/v2
custom.group.v2.registration.api.ccm.core.api.clientId=cb0b69bb997bf158bd16427b51dd3eb0
custom.group.v2.registration.api.ccm.core.api.clientSecret=a063606c0869164d0bbc4a5c86b29e37
custom.group.v2.registration.api.ccm.core.api.scopes=contactpoint.admin,plangroup.admin

#PTM Sample Coverage
custom.groupregistratation.v2.group.coverage.url=https://mm454-54mm4-4-4.azure-api.net/apim_proxy_echo_/private/opstest/api/corp/gateway/group/coverages/delegation/v3
custom.groupregistratation.v2.group.coverage.api.clientId=cb0b692c997bf158bd16427b51dd3eb0
custom.groupregistratation.v2.group.coverage.api.clientSecret=a063606c086bb64d075c4a5c86b29e37
custom.groupregistratation.v2.group.coverage.jwt.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
custom.groupregistratation.v2.groups.identity.lookup.blocked.plan.ids=09874,05442,05447,06349,06408,08262,05570,05634,05687,05709,07248,07427,07454,07493,07498,07499,07501,07514,07529,07651,07700,07701,08505,08506,08507,08510,07704,07716,08261,03623,03669,03724,03733,03734,03738,03850,03947,03948,03953,03964,03972,03974,03977,04047,04048,04064,04073,04313,04314,04319,04320,01245,01249,01251,04351,04352,04353,04384,01647,01678,01709,01732,01751,01759,01779,01780,01832,01867,01953,01961,02020,02076,02101,02126,02272,02379,02602,02611,02651,02741,02790,03049,03054,03055,03059,03160,03973,07926,14918,12114,14836,12066,14834,00383,12109,12113,14835,30792,10823,00794,03294,03218,03297,02069,04746,04718,16520,16519,16517,01994
custom.groupregistratation.v2.blue.groove.products=12833,12834,12835,12838,12840,12841,12343,02715,12823,12824,12825,12826,12831,12832,12342,02792,12813,12814,12815,12816,12817,12819,12346,02770,12823,12824,12825,12826,12831,12832,12342,02792,09761,09762,09763,09765,09771,09772,12813,12814,12815,12816,12817,12819,12346,02770,09750,09751,09752,09753,09758,09760,12833,12834,12835,12838,12840,12841,12343,02715,09773,09774,09775,09776,09777,09778

#PTM Auto Delegation
custom.groupregistratation.v2.auto.delegation.service.url=https://mm454-54mm4-4-4.azure-api.net/apim_proxy_echo_/private/opstest/api/corp/gateway/groups/auto/delegation/create/v2
custom.groupregistratation.v2.auto.delegation.api.clientId=cb0b692bb97bf158bd16427b51dd3eb0
custom.groupregistratation.v2.auto.delegation.api.clientSecret=a063606c086916bb075c4a5c86b29e37
custom.groupregistratation.v2.auto.delegation.service.api.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30

#LLM Assignment API
manual.mcp.v2.assignment.service.desc=This API will be used for Manual LLM Assignment
manual.mcp.v2.assignment.service.uri=/corp/gateway/mcp/assignment/v2
manual.mcp.v2.assignment.service.route=direct:processLLMAssignment

#LLM Assignment Trigger API
mcp.assignment.v2.retry.service.api.uri=corp/gateway/ifp/mcp/assignment/trigger/v2
mcp.assignment.v2.retry.service.api.processor=direct:mcpAssignmentRetryProcessor
mcp.assignment.v2.retry.service.api.desc=This api is used to re-trigger the failed LLM Assignments requests
mcp.assignment.v2.service.processor=seda:mcpAssignmentAPIRetry?concurrentConsumers=1

#LLM retry config
mcp.assignment.v2.retry.service.configuration.processFromDays=30
mcp.assignment.v2.retry.service.configuration.rowCount=100
mcp.assignment.v2.retry.service.configuration.lastUpdatedMinutes=10
mcp.assignment.v2.retry.service.configuration.minutes=1440
mcp.assignment.v2.retry.service.configuration.maxIterations=-1

#LLM proxy add app service endpoint /corp/gateway/mcp/assignment/v2
custom.group.v2.registration.mcp.assignment.service.url=https://mm454-54mm4-4-4.azure-api.net/apim_proxy_echo_/private/opstest/api/corp/gateway/mcp/assignment/v3
custom.group.v2.registration.mcp.assignment.service.clientId=9abbc6f34e06a95eca70982348ed228e
custom.group.v2.registration.mcp.assignment.service.clientSecret=037c99a96aebb9b857aeff280488d82e

#LLM notification config
mcp.assignment.v2.retry.service.notification.from=defaultFrom
mcp.assignment.v2.retry.service.notification.to=prabhu.rc@example.com
mcp.assignment.v2.retry.service.notification.subject=LLM assignment job status : releasetest
mcp.assignment.v2.retry.service.notification.template=userSuppliedTemplate

#LLM AEM
mcp.v2.assignment.service.virtual.mcp.aem.url=https://www.webh70.corp.larplarp.com/bin/cms/corpa/services/group?apiResource=ifp-virtual-mcp-assignment&lang=en
mcp.v2.assignment.service.killswitch.aem.url=https://www.webh70.corp.larplarp.com/bin/cms/corpa/services/group?apiResource=kill-switch-api&lang=en

#LLM Change Family ISL
manual.mcp.v2.assignment.service.api.cowsws.address=https://mm454-54mm4-4-4.azure-api.net/apim_proxy_esbh05dp_8819_npn/FacetsWebServiceLibrary/FaWsvcInpSampleshipMaintenance_v26.asmx
manual.mcp.v2.assignment.service.api.cows.connection.error=Technical exception occurred while calling change family ISL service

#Splunk
custom.group.upgrade.v2.splunk.audit.url=https://mm454-54mm4-4-4.azure-api.net/apim_proxy_echo_/private/opstest/api/corp/gateway/portal/splunk/auditing/events/v4
custom.group.upgrade.v2.splunk.audit.clientid=cb0b692c99bbf158bd16427b51dd3eb0
custom.group.upgrade.v2.splunk.audit.clientsecret=a063606c086bb64d075c4a5c86b29e37
custom.group.upgrade.v2.splunk.audit.host=opstest

#HikariCP Configuration for Facets
example.api.cows.hikari.maximumPoolSize=10
example.api.cows.hikari.minimumIdle=5
example.api.cows.hikari.connectionTimeout=30000
example.api.cows.hikari.idleTimeout=600000
example.api.cows.hikari.maxLifetime=1800000
example.api.cows.hikari.poolName=FacetsHikariPool
example.api.cows.hikari.cachePrepStmts=true
example.api.cows.hikari.prepStmtCacheSize=250
example.api.cows.hikari.prepStmtCacheSqlLimit=2048

example.service.api.cows.url=jdbc:oracle:thin:@MXMEMX.test.example.com:12521:MEXGMS
example.service.api.cows.username=AIPROUSR
example.service.api.cows.password=qeJm7QL4_9yQUdJ8

logging.level.sun.rmi.transport=WARN
logging.level.sun.rmi.loader=WARN
logging.level.sun.rmi.registry=WARN
logging.level.sun.util.logging=WARN


# spring log4j properties
logging.level.root=DEBUG
logging.file=logs/
logging.file.name=logs/message.log
logging.pattern.rolling-file-name=logs/message_%d{yyyyMMdd}_%i.log
logging.pattern.console=%-5p | %d{yyyy-MM-dd HH:mm:ss.SSS} | BuyBluePseMemAutoRegAzSrvV1  [%t] %C{2} %m%n
logging.file.max-history=30
logging.file.max-size=10MB
logging.file.total-size-cap=100MB